import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Providers } from "@/app/providers";
import { Button } from "@nextui-org/button";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
      // <html lang="en" className='dark'>
      <html lang="en">
      <body className={inter.className}>
      <Providers>
          <Button>Click me</Button>
          {children}
      </Providers>
      </body>
    </html>
  )
}
